branch-defaults:
  default:
    environment: router-dev
    group_suffix: null
global:
  application_name: router
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
