version: 0.2
env:
  secrets-manager:
    LOGIN: prod/sonar:sonartoken2
    HOST: prod/sonar:HOST
    Organization: prod/sonar:Organization
    Project: prod/sonar:Project2
phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - echo "installing dependencies..."
      - apt-get update
      - apt-get install -y jq
      - go mod vendor
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - export PATH=$PATH:/sonar-scanner-3.3.0.1492-linux/bin/
  build:
    commands:
      - echo "zipping deployment package..."
      - cd checkin/anti-fraud/
      - GOOS=linux GOARCH=amd64 go build -o anti-fraud-bin
      - zip -g deployment_package.zip anti-fraud-bin
  post_build:
    commands:
      - echo "updating lambda function..."
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
      - aws lambda update-function-code --function-name anti_fraud_checkin --zip-file fileb://deployment_package.zip
      - echo "DONE"
