version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.16
    commands:
      - echo "installing dependencies..."
      - go mod vendor
  build:
    commands:
      - echo "zipping deployment package..."
      - cd checkin/record
      - GOOS=linux GOARCH=amd64 go build -o record-checkin-bin
      - zip -g deployment_package.zip record-checkin-bin
  post_build:
    commands:
      - echo "updating lambda function..."
      - aws lambda update-function-code --function-name record_checkin --zip-file fileb://deployment_package.zip
      - echo "DONE"
