version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.16
    commands:
      - echo "installing dependencies..."
      - go mod vendor
  build:
    commands:
      - echo "zipping deployment package..."
      - cd rule-engine/verify-rules/
      - GOOS=linux GOARCH=amd64 go build -o verify-rules-bin
      - zip -g deployment_package.zip verify-rules-bin
  post_build:
    commands:
      - echo "updating lambda function..."
      - aws lambda update-function-code --function-name live_verify_rules --zip-file fileb://deployment_package.zip
      - echo "DONE"
